In [1]:
import pandas as pd
import numpy as np
import nltk

from data_model import *

In [3]:
data_model = QuoraQuestionsModel(DataConfig())
#data_model.load_dicts()

In [ ]:
labels = pd.read_csv(data_model.config.train_file, usecols=["target"])

In [ ]:
from collections import Counter
counts = Counter(labels.target.values)

In [ ]:
counts

In [7]:
data = open('../data/processed/dev/pos.txt').readlines()

In [8]:
len(data)

4040

In [6]:
len(data)

61265

In [2]:
data_model = QuoraQuestionsModelStreamer(DataConfig())

In [3]:
input_data, seq_length, labels = data_model.data_reader("../data/processed/dev/")

In [12]:
labels.shape

(65305,)

In [11]:
labels[:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
import sys
sys.getsizeof(input_data)

7836600128

In [58]:
import random
random.seed(0)

In [59]:
np.random.randint(0, 2, 10, np.intp)

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [62]:
np.random.randint(0, 2, 10, np.intp)

array([0, 0, 1, 1, 1, 0, 0, 1, 1, 1])

In [63]:
np.random.randint(0, 2, 10, np.intp)

array([0, 0, 1, 1, 0, 1, 0, 1, 1, 0])

In [72]:
line = '1 2 3 4 0\n'
line_list = line.split(" ")
label = line_list[-1]
sequence = np.array(line_list[:-1], dtype=np.intp)

In [73]:
sequence

array([1, 2, 3, 4])

In [74]:
int(label)

0

In [75]:
label

'0\n'