In [1]:
import pandas as pd
import numpy as np
import nltk

from data_model import *

In [24]:
file_pos = "../data/processed/parsed_train_pos.txt"
file_neg = "../data/processed/parsed_train_neg.txt"

In [25]:
seq_lengths = []
with open(file_pos) as fi:
    for line in fi:
        seq_lengths.append(len(line))

In [3]:
labels = np.random.randint(0, 2, 10, np.intp)

In [4]:
np.random.choice([0, 1], size=10, replace=True, p=[0.8, 0.2])

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [5]:
np.random.choice([0, 1], size=10, replace=True, p=[0.8, 0.2])

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 1])

In [6]:
np.random.choice([0, 1], size=10, replace=True, p=[0.8, 0.2])

array([1, 0, 0, 0, 1, 0, 0, 1, 0, 0])